log-level: silent
listeners:
  - name: trojan
    type: trojan
    port: 5505
    listen: '::'
    users:
      - username: das
        password: ff057152-e2b0-4a90-a6f6-d9cd0e796f09
    certificate: ./server.crt
    private-key: ./server.key
  - name: vless
    type: vless
    port: 7707
    listen: '::'
    users:
      - username: das
        uuid: ff057152-e2b0-4a90-a6f6-d9cd0e796f09
        flow: xtls-rprx-vision
    reality-config:
      dest: dingtalk.com:443
      private-key: IbNuIOUqjihOgib0MYC5fqiHnqLYMtjSIr1kVeKOwaw
      short-id:
        - 150f6838bd518c8d
      server-names:
        - down.dingtalk.com
  - name: hy2
    type: hysteria2
    port: 6606
    listen: '::'
    users:
      das: ff057152-e2b0-4a90-a6f6-d9cd0e796f09
    up: 100
    down: 100
    certificate: ./server.crt
    private-key: ./server.key
  - name: ss
    type: shadowsocks
    port: 9909
    listen: '::'
    cipher: 2022-blake3-aes-256-gcm
    password: NwrQy7u4V5v9p6uHqsz4EJ0Eut4yD5O7M//bQPbzce8=
    udp: true
